### ISSUE TITLE
Can not load two different sound files

### ISSUE THREAD

**Issue by KapitanPL** [melihhakanpektas/flutter_midi_pro#14]
I tried to write an app that used two different sound fonts. 

Android App, Two differente instances of "instrument", each should hold its own MidiPro class. 

However when playing both instruments play the same file. 

Although it is not clear that MidiPro is a singleton. Or shares memory, or whatever...

**Comment by KapitanPL** [comment]
Hi @melihhakanpektas 
I am trying to create a patch to allow that. 

Can you help me?

what is happening in 

synth.loadAllInstruments(sf)
synth.channels[0].programChange(instrumentIndex)

How are instruments stored in memory? What if I call loadAllInstruments for two different instances of sf. 
What are the channels?

I partially succeeded, but so far I am unable to correctly tell the index of instruments. So I need to understand how are they stored/loaded to memory. 

Is the engine below (the java files) documented somewhere?

**Comment by melihhakanpektas** [comment]
Hello @KapitanPL,

The `synth` variable is a `SoftSynthesizer` object. The `synth.loadAllInstruments()` method loads all the instruments available in the Soundfont to synth variable. Actually, there is also a `loadInstrument` method to load one or more specific instruments from the Soundfont, but I couldn't get it to work consistently. Since the `loadAllInstruments` method is the only one I could consistently use, I stick with it.

The `channel` list represents the channels of the synthesizer. Up to 16 synthesizer channels are supported. Ideally, I would have added support for individual channels using `flutter_midi_pro`, but I couldn't find a way to handle channels separately in Swift, so I left it out.

The `SoftSynthesizer` object is quite complex, and I haven't had enough opportunity to thoroughly examine it. You can explore it further [here](https://github.com/melihhakanpektas/flutter_midi_pro/blob/master/android/src/main/kotlin/com/melihhakanpektas/midisynthesizer/sound/SoftSynthesizer.java).

Thank you for your intresting in developing the flutter_midi_pro 🚀

**Comment by KapitanPL** [comment]
Does it mean that different sound fonts can be stored in different channels? Or what the channels actually represent?

**Comment by melihhakanpektas** [comment]
> Does it mean that different sound fonts can be stored in different channels? Or what the channels actually represent?

I’ve never tried loading different soundfont files at the same time, but I’m sure that the instruments of the same soundfont file can be loaded into different channels. For example: 
`synth.channels[0].programChange(0)`
`synth.channels[1].programChange(1)`
...
`synth.channels[15]` is the last channel.

**Comment by KapitanPL** [comment]
@melihhakanpektas Thanks, already found that. :) 
The java underneath your kotlin/dart seems pretty powerfull. 

I guess in the future it might support loading two soundfiles. For now I limitted my app to only single sf2. 
Thanks anyway. 

For now I have forked your midi-pro and I am slowly adding more functions. (listing available instruments.) But for now only on Android.
