### ISSUE TITLE
How to use two different sf2 files at same time while playing ?

### ISSUE THREAD

**Issue by sohamprodt** [melihhakanpektas/flutter_midi_pro#15]
I want to play two sf2 files simultaneously using two different instances but observed that both instance override sound when we use loadSoundFont function. Can you please help out me in this situation ?

**Comment by melihhakanpektas** [comment]
For now, this is not possible because we learned that the package used on Android is a singleton (it has not been tested on iOS. Maybe it’s the same.) This was a serious problem and I'm currently working on that. Thank you for your report.

**Comment by KapitanPL** [comment]
I tried to deal with it, not that easy... 
For now I decided to use single soundfont and let only user have two or more instruments from that soundfont.

**Comment by melihhakanpektas** [comment]
Check out [this branch](https://github.com/melihhakanpektas/flutter_midi_pro/tree/singleton_fix) for multiple soundfonts, MIDI channels, and bank selection features JUST for Android. It’s still a singleton, but it should be to prevent some possible errors for now, maybe forever. 

The Java package that was used was slow and incomprehensible. I am currently trying to integrate FluidSynth, which is a C library. It’s both faster and more customizable. For now, I will add the basic features. Since FluidSynth has its own wiki, development can be scaled up faster.

The last commit of the singleton_fix branch includes new features and it’s working just for Android. You can use this branch in your project for now.

**Comment by KapitanPL** [comment]
Seems nice. 
I am on the way to try it. But in the mean time I added to your previous iteration a possibility to list instruments. (So it can appear in a combobox for user to select) 
Can you add it to this fluidsynth based branch? 

If not, I will try. :)

**Comment by KapitanPL** [comment]
Ah... seems you add only compiled objects ... so I can not see the original source code. :) I need to go to fluidsync githbu

**Comment by melihhakanpektas** [comment]
Finally updated the new version of the flutter_midi_pro plugin. Nearly everything changed in this package but you can manage everything of the soundfont and midi channels.

**Comment by sohamprodt** [comment]
Thank you so much @melihhakanpektas . Kudos to your efforts
